### ISSUE TITLE
Error: Encountered an UNKNOWN path, report this to the developer!

### ISSUE THREAD

**Issue by SecurityAura** [CyberCX-DFIR/usnjrnl_rewind#3]
Since the previous issue regarding that error got closed, I'll start a new one and make sure to respond to it and assist on fixing it however I can!

Error is in the title.

![image](https://github.com/user-attachments/assets/581edb27-76c4-4e96-8e95-9c2b6c42eb57)

When I first started using the tool when it just came out, I didn't really encounter it. Now it seems that I encounter if every single time I run it. The script completes and an output is generated. Though I assume that it may be incomplete because of that.

The MFT and UsnJrnl are collected through a Velociraptor collector (0.6.9), then parsed with MFECmd.exe.

Anything I can provide to assist in fixing this? That would also not expose the data of the system's MFT and UsnJrnl I'm running the tool against?

**Comment by ydkhatri** [comment]
This is likely due to an issue with the way Velociraptor used to retrieve/handle NTFS files in versions prior to 0.7.0. Due to incorrect reading of the MFT for certain very large sparse files, such as the USNJRNL and sometimes $MFT, the files collected would be incomplete. I identified this and provided bugfixes (about a year back) which were incorporated in 0.7.0. See https://github.com/Velocidex/velociraptor/issues/2785

Please upgrade to a newer version of Velociraptor or manually pull the files and try again.

**Comment by SecurityAura** [comment]
This would make perfect sense given our use of Velociraptor.

I've already generated a new collector from the latest version 0.72.0. I don't know when I'll be able to use/test it out (depends on when an IR comes in).

I feel like this would solve the issue however. So as to not leave that issue open for nothing, I feel like we can close it and should this not fix the error, we could re-open it?

**Comment by ydkhatri-cybercx** [comment]
Closing this one, let me know if you encounter it again.
